name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Start the SSH agent
          eval "$(ssh-agent -s)"
          
          # Add the private key directly from the secret
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          
          # Disable strict host key checking for simplicity (optional)
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Run SSH Command
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "echo 'Connected successfully!'"
